config/routes.rb
Rails.application.routes.draw do
  root "homepage#index"
  get "chart_data" => "homepage#chart_data", as: :chart_data

  scope "auth" do
    devise_for :users
  end

  resources :pos, only: [ :index ] do
    collection do
      get :search
      get :queue
      post :check_out
      patch :in_progress
      patch :cancel
      patch :complete
    end
  end

  resources :users
  resources :products
  resources :categories
  resources :sales

  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/partials/_delete_modal.html.haml
- if params[:action] == "show"
  %button.btn.btn-danger.m-l-10{"data-bs-target" => "#deleteModal#{object_id}", "data-bs-toggle" => "modal", type: "button"}
    %i.ti.ti-trash
    Delete
- else
  %button.btn.btn-outline-danger.btn-sm.btn-delete{"data-bs-target" => "#deleteModal#{object_id}", "data-bs-toggle" => "modal", type: "button"}
    %i.ti.ti-trash

.modal.fade{id: "deleteModal#{object_id}", "aria-hidden" => "true", "aria-labelledby" => "deleteModal#{object_id}Label", "data-bs-backdrop" => "static", "data-bs-keyboard" => "false", tabindex: "-1"}
  .modal-dialog.modal-dialog-centered
    .modal-content
      .modal-header
        %h1#staticBackdropLabel.modal-title.fs-5
          %i.ti.ti-trash
          Delete Data
        %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", type: "button"}
      .modal-body.text-center
        %br/
        %h5 Are you sure to delete this record?
        %br/
      .modal-footer
        %button.btn.btn-light{"data-bs-dismiss" => "modal", type: "button"} Cancel
        = link_to path, method: :delete, class: "btn btn-danger" do
          Delete

app/views/partials/_navbar.haml
/ Header Start
%header.app-header
  %nav.navbar.navbar-expand-lg.navbar-light
    %ul.navbar-nav
      %li.nav-item.d-block.d-xl-none
        %a#headerCollapse.nav-link.sidebartoggler.nav-icon-hover{href: "javascript:void(0)"}
          %i.ti.ti-menu-2
      %li.nav-item
        %a.nav-link.nav-icon-hover{href: "javascript:void(0)"}
          %i.ti.ti-bell-ringing
          .notification.bg-primary.rounded-circle
    #navbarNav.navbar-collapse.justify-content-end.px-0
      %ul.navbar-nav.flex-row.ms-auto.align-items-center.justify-content-end
        %li.nav-item.dropdown
          %a#drop2.nav-link.nav-icon-hover{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", href: "javascript:void(0)"}
            - if current_user.picture.attached?
              = image_tag current_user.picture.variant(resize: "35x35"), class: "rounded-circle", alt: ""
            - else
              %img.rounded-circle{alt: "", height: "35", src: "/images/profile/user-1.jpg", width: "35"}/
          .dropdown-menu.dropdown-menu-end.dropdown-menu-animate-up{"aria-labelledby" => "drop2"}
            .message-body
              = link_to current_user, class: "d-flex align-items-center gap-2 dropdown-item" do
                %i.ti.ti-user.fs-6
                %p.mb-0.fs-3 My Account
              = link_to destroy_user_session_path, method: :delete, class: "btn btn-outline-primary mx-3 mt-2 d-block", "aria-current" => "page" do
                Logout

app/views/partials/_pagination.html.haml
.row
  .col-md-12.text-end
    = paginate(@grid.assets,theme: 'bootstrap-5', pagination_class: "pagination-sm flex-wrap justify-content-center", nav_class: "d-inline-block")

app/views/partials/_sidebar.html.haml
/ Sidebar Start
%aside.left-sidebar
  / Sidebar scroll
  %div
    .brand-logo.d-flex.align-items-center.justify-content-between
      = link_to root_url, class: "text-nowrap logo-img" do
        = image_tag "logo.png", width: "180"
      #sidebarCollapse.close-btn.d-xl-none.d-block.sidebartoggler.cursor-pointer
        %i.ti.ti-x.fs-8
    / Sidebar navigation
    %nav.sidebar-nav.scroll-sidebar{"data-simplebar" => ""}
      %ul#sidebarnav
        %li.nav-small-cap
          %i.ti.ti-dots.nav-small-cap-icon.fs-4
          %span.hide-menu Home
        %li.sidebar-item
          = link_to root_url, class: "sidebar-link #{menu_active?("homepage")}", "aria-expanded" => "false" do
            %span
              %i.ti.ti-layout-dashboard
            %span.hide-menu Dashboard
        %li.sidebar-item
          = link_to pos_url, class: "sidebar-link #{menu_active?("pos")}", "aria-expanded" => "false" do
            %span
              %i.ti.ti-cash
            %span.hide-menu Point of Sale
        %li.sidebar-item
          = link_to sales_url, class: "sidebar-link #{menu_active?("sales")}", "aria-expanded" => "false" do
            %span
              %i.ti.ti-report-money
            %span.hide-menu Sale Records
        %li.nav-small-cap
          %i.ti.ti-dots.nav-small-cap-icon.fs-4
          %span.hide-menu Inventory
        %li.sidebar-item
          = link_to products_url, class: "sidebar-link #{menu_active?("products")}", "aria-expanded" => "false" do
            %span
              %i.ti.ti-package
            %span.hide-menu Products
        %li.sidebar-item
          = link_to categories_url, class: "sidebar-link #{menu_active?("categories")}", "aria-expanded" => "false" do
            %span
              %i.ti.ti-article
            %span.hide-menu Categories
        %li.nav-small-cap
          %i.ti.ti-dots.nav-small-cap-icon.fs-4
          %span.hide-menu Settings
        %li.sidebar-item
          = link_to users_url, class: "sidebar-link #{menu_active?("users")}", "aria-expanded" => "false" do
            %span
              %i.ti.ti-users
            %span.hide-menu Users
      
      .unlimited-access.hide-menu.bg-light-primary.position-relative.mb-7.mt-5.rounded
        .d-flex
          .unlimited-access-title.me-3
            %h6.fw-semibold.fs-4.mb-6.text-dark.w-85 v0.0.1-beta
            %a.btn.btn-primary.fs-2.fw-semibold.lh-sm{href: "https://vandysodanheang.info", target: "_blank"} By Vandy Sodanheang
      