config/routes.rb
Rails.application.routes.draw do
  root "homepage#index"
  get "chart_data" => "homepage#chart_data", as: :chart_data

  scope "auth" do
    devise_for :users
  end

  resources :pos, only: [ :index ] do
    collection do
      get :search
      get :queue
      post :check_out
      patch :in_progress
      patch :cancel
      patch :complete
    end
  end

  resources :users
  resources :products
  resources :categories
  resources :sales

  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/pos_controller.rb
class PosController < ApplicationController
  layout :set_layout
  before_action :set_sale, only: %i[ in_progress cancel complete ]

  def index
  end

  def search
    search_value = params[:search_value]
    products = Product.where(status: "Active")
    products = products.name_like(search_value) if search_value.present?
    products = products.order(:name)

    @products = products.includes(:category).map do |product|
      {
        id: product.id,
        name: product.name.truncate(20),
        picture: url_for(product.picture_as_thumbnail),
        category: product.category.name,
        sizes: product.product_sizes&.map do |pps|
          {
            id: pps.id,
            size: pps.size,
            price: pps.price
          }
        end
      }
    end

    render json: @products
  rescue => e
    render json: { error: e.message }, status: :unprocessable_entity
  end

  def check_out
    sale = build_sale
    if sale.save
      render json: { id: sale.id, message: "Check out success", pdf_url: sale_url(sale, format: :pdf) }
    else
      render json: { error: sale.errors.full_messages.join(", ") }, status: :unprocessable_entity
    end
  end

  def queue
    @pending_sales = Sale.where(status: "Pending").order(:created_at)
    @in_progress_sales = Sale.where(status: "In Progress").order(:created_at)
  end

  def in_progress
    if @sale.update(status: "In Progress")
      redirect_to queue_pos_path, notice: "Sale-#{@sale.code} has been moved to in progress!"
    else
      render :queue, notice: "Failed to move Sale-#{@sale.code} to in progress!"
    end
  end

  def cancel
    @sale = Sale.find(params[:id])
    if @sale.update(status: "Canceled")
      redirect_to queue_pos_path, notice: "Sale-#{@sale.code} has been canceled!"
    else
      render :queue, notice: "Failed to cancel Sale-#{@sale.code}!"
    end
  end

  def complete
    @sale = Sale.find(params[:id])
    if @sale.update(status: "Completed")
      redirect_to queue_pos_path, notice: "Sale-#{@sale.code} has been completed!"
    else
      render :queue, notice: "Failed to complete Sale-#{@sale.code}!"
    end
  end

  private
    def set_layout
      "pos"
    end

    def set_sale
      @sale = Sale.find(params[:id])
    end

    def build_sale
      Sale.new do |s|
        s.customer_name = check_out_params[:customer_name]
        s.customer_phone_number = check_out_params[:customer_phone_number]
        s.note = check_out_params[:note]
        s.user = current_user
        s.product_sales = build_product_sales
        s.amount = s.product_sales.sum(&:price)
        s.total_items = s.product_sales.size
      end
    end

    def build_product_sales
      check_out_params[:products].values.map do |product|
        price = ProductSize.find(product[:size_id]).price
        ProductSale.new do |ps|
          ps.product_size_id = product[:size_id]
          ps.price = price
          ps.sugar_level = product[:sugar_level]
        end
      end
    end

    def check_out_params
      params.require(:check_out).permit(:customer_name, :customer_phone_number, :note, products: [ :size_id, :sugar_level ])
    end
end

app/views/pos/index.html.haml
%br/
%br/
.row
  .col-6
    = link_to root_path, class: "btn btn-light" do
      %i.ti.ti-arrow-left
      Back to System
    = link_to queue_pos_path, class: "btn btn-warning m-l-10" do
      %i.ti.ti-hourglass-high
      Queue
  .col-6.text-end
    %button.btn.btn-primary{type: "button", id: "btn-checkout", "data-bs-target" => "#checkout-modal", "data-bs-toggle" => "modal", type: "button", "disabled" => ""}
      %i.ti.ti-shopping-cart
      Checkout
%br/

- if notice.present?
  .row
    .col-md-12
      .alert.alert-success{role: "alert"}
        %b Message: 
        = notice

#checkout-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "checkout-modal-label", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %h1#checkout-modal-label.modal-title.fs-5
          %i.ti.ti-shopping-cart
          Are You Sure?
        %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", type: "button"}
      .modal-body
        .table-responsive
          %table.table
            %tbody
              %tr
                %td
                  %i.ti.ti-cup
                  Total Drink
                %th#checkout-total-drink
                  0 Drink
              %tr
                %td
                  %i.ti.ti-cash
                  Total Price
                %th#checkout-total-price
                  $ 0.00
        .row
          .col-sm-12
            %input#customer-name-input.form-control{placeholder: "Customer's Name", type: "text"}
            %br/ 
            %input#customer-phone-number-input.form-control{placeholder: "Phone Number", type: "text"}
            %br/
            %textarea#customer-note-input.form-control{placeholder: "Note", rows: "3"}
      .modal-footer
        %button.btn.btn-light{"data-bs-dismiss" => "modal", type: "button"} Close
        %button#btn-submit-checkout.btn.btn-primary{type: "button"} Check Out

#checkout-success-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "checkout-success-modal-label", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %h1#checkout-success-modal-label.modal-title.fs-5
          %i.ti.ti-check
          Checked Out!
        %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", type: "button"}
      .modal-body
        %p Your order has been successfully checked out.
        %p Thank you for using our system.
      .modal-footer
        %a#btn-print-receipt.btn.btn-success{href: "#", target: "_blank"}
          %i.ti.ti-printer
          Print Receipt
        %button.btn.btn-light{"data-bs-dismiss" => "modal", type: "button"} Close

#checkout-error-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "checkout-error-modal-label", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %h1#checkout-error-modal-label.modal-title.fs-5
          %i.ti.ti-alert
          There Was An Error
        %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", type: "button"}
      .modal-body
        %p There was an error when checking out your order.
        %p Please try again later.
      .modal-footer
        %button.btn.btn-danger{"data-bs-dismiss" => "modal", type: "button"} Close
        

.row
  .col-sm-12.col-lg-7.d-flex.align-items-stretch
    .card.w-100.m-h-50rem
      .card-body.p-4
        .row
          .col-md-6
            %h5.card-title.fw-semibold.mb-4
              %i.ti.ti-cash
              Point of Sale
          .col-md-6
            %input#search-products.form-control{placeholder: "Search Product", type: "text"}
        %br/
        .row#products-container
                    
  
  .col-sm-12.col-lg-5.d-flex.align-items-stretch
    .card.w-100
      .card-body.p-4
        %h5.card-title.fw-semibold.mb-4
          %i.ti.ti-shopping-cart
          Order Summary
          %span#summary-total-price{style: 'float: right;'}
            $ 0.00
        %hr/
        .row
          .col-md-12
            .table-responsive
              %table.table
                %thead
                  %tr
                    %th{style: "width: 35%"} Product
                    %th.text-center{style: "width: 25%"} Sugar
                    %th.text-center{style: "width: 10%"} Size
                    %th.text-center{style: "width: 20%"} $ Price
                    %th.text-center{style: "width: 10%"}
                %tbody#order-summary-container
                  %tr
                    %td.text-end{colspan: "3"} Total
                    %td.text-center#total-price
                      %strong
                        $ 0.00
                    %td
                      %button#btn-remove-all-products.btn.btn-danger.btn-sm{type: "button"}
                        %i.ti.ti-trash
            

app/views/pos/queue.html.haml
%br/
%br/
.row
  .col-12
    = link_to root_path, class: "btn btn-light" do
      %i.ti.ti-arrow-left
      Back to System
    = link_to pos_path, class: "btn btn-primary m-l-10" do
      %i.ti.ti-cash
      Point of Sale
%br/

- if notice.present?
  .row
    .col-md-12
      .alert.alert-success{role: "alert"}
        %b Message: 
        = notice

.row
  .col-sm-12.col-lg-6.d-flex.align-items-stretch
    .card.w-100.m-h-50rem
      .card-body.p-4
        %h5.card-title.fw-semibold.mb-4
          %i.ti.ti-hourglass-high
          Pending Orders
          %span.badge.bg-secondary.rounded-3.fw-semibold.float-rigt
            = "#{@pending_sales.size} Orders"
        - @pending_sales.each do |sale|
          .row
            .col-4
              %p
                Code:
                %b= sale.code.truncate(11)
            .col-2
              %p
                Name:
                %b= sale.customer_name
            .col-2
              %p
                Amount:
                %b= "$ #{sale.amount&.round(2)}"
            .col-2
              %p
                Items:
                %b= "#{sale.total_items} Items"
            .col-2.text-end
              = link_to cancel_pos_path(id: sale.id), method: :patch, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" do
                %i.ti.ti-trash
              = link_to in_progress_pos_path(id: sale.id), method: :patch, class: "btn btn-primary btn-sm m-l-10" do
                %i.ti.ti-arrow-right
          .row
            .col-12
              %p
                %b Note:
                = sale.note
          .table-responsive
            %table.table.custom-table
              %thead
                %tr
                  %th Item Name
                  %th Size                
                  %th Sugar Level
                  %th $ Price
              %tbody
                - sale.product_sales.each do |product_sale|
                  %tr
                    %td= product_sale.product_size.product.name
                    %td= product_sale.product_size.size
                    %td= "#{product_sale.sugar_level} %"
                    %td= "$ #{product_sale.price&.round(2)}"
          %hr/
                    
  .col-sm-12.col-lg-6.d-flex.align-items-stretch
    .card.w-100
      .card-body.p-4
        %h5.card-title.fw-semibold.mb-4
          %i.ti.ti-clock-hour-4
          In Progress Orders
          %span.badge.bg-warning.rounded-3.fw-semibold.float-rigt
            = "#{@in_progress_sales.size} Orders"
        - @in_progress_sales.each do |sale|
          .row
            .col-4
              %p
                Code:
                %b= sale.code.truncate(11)
            .col-2
              %p
                Name:
                %b= sale.customer_name
            .col-2
              %p
                Amount:
                %b= "$ #{sale.amount&.round(2)}"
            .col-2
              %p
                Items:
                %b= "#{sale.total_items} Items"
            .col-2.text-end
              = link_to cancel_pos_path(id: sale.id), method: :patch, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" do
                %i.ti.ti-trash
              = link_to complete_pos_path(id: sale.id), method: :patch, class: "btn btn-success btn-sm m-l-10" do
                %i.ti.ti-check
          .row
            .col-12
              %p
                %b Note:
                = sale.note
          .table-responsive
            %table.table.custom-table
              %thead
                %tr
                  %th Item Name
                  %th Size                
                  %th Sugar Level
                  %th $ Price
              %tbody
                - sale.product_sales.each do |product_sale|
                  %tr
                    %td= product_sale.product_size.product.name
                    %td= product_sale.product_size.size
                    %td= "#{product_sale.sugar_level} %"
                    %td= "$ #{product_sale.price&.round(2)}"
          %hr/