config/routes.rb
Rails.application.routes.draw do
  root "homepage#index"
  get "chart_data" => "homepage#chart_data", as: :chart_data

  scope "auth" do
    devise_for :users
  end

  resources :pos, only: [ :index ] do
    collection do
      get :search
      get :queue
      post :check_out
      patch :in_progress
      patch :cancel
      patch :complete
    end
  end

  resources :users
  resources :products
  resources :categories
  resources :sales

  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/sale.rb
class Sale < ApplicationRecord
  before_create :generate_code

  belongs_to :user, optional: true
  has_many :product_sales, dependent: :destroy

  STATUS = [ "Pending", "In Progress", "Canceled", "Completed" ]

  scope :code_like, ->(value) { where("code iLIKE ?", "%#{value.squish}%") }

  STATUS.each do |status_name|
    scope status_name.downcase, -> { where(status: status_name) }

    define_method "#{status_name.downcase.parameterize.underscore}?" do
      status == status_name
    end
  end

  private
    def generate_code
      self.code = "#{SecureRandom.hex(4).upcase}-#{Time.now.strftime('%Y%m%d%H%M%S')}"
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %i[ show edit update destroy ]

  # GET /sales
  def index
    @grid = SalesGrid.new(grid_params) do |scope|
      scope.page(params[:page]).per(10)
    end
  end

  # GET /sales/1
  def show
    respond_to do |format|
      format.html
      format.pdf do
        pdf = generate_receipt
        send_data pdf.render, filename: "invoice_#{@sale.code}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  def create
    @sale = Sale.new(sale_params)

    if @sale.save
      redirect_to @sale, notice: "Sale was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /sales/1
  def update
    if @sale.update(sale_params)
      redirect_to @sale, notice: "Sale was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /sales/1
  def destroy
    @sale.destroy!
    redirect_to sales_url, notice: "Sale was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:code, :status, :customer_name, :customer_phone_number, :note, :user_id)
    end

    def grid_params
      params.fetch(:sales_grid, {}).permit(
        :status,
        :code,
        :created_at_gt,
        :created_at_lt
      )
    end

    def generate_receipt
      Prawn::Document.new do |pdf|
        pdf.text "RECEIPT", align: :center, size: 24, style: :bold
        pdf.move_down 20

        # Shop details
        pdf.text "Cafe POS System", size: 14, style: :bold
        pdf.text "Phnom Penh, Cambodia", size: 12
        pdf.move_down 5
        pdf.text "Invoice: #{@sale.code}", size: 12, style: :bold
        pdf.text "Date: #{@sale.created_at.strftime('%d / %B / %Y')}", size: 12
        pdf.text "Cashier: #{@sale.user&.name}", size: 12
        pdf.text "Phone: 012 XXX XXX", size: 12
        pdf.move_down 20

        # Line items
        pdf.table(line_items_table, width: 500, position: :center, cell_style: { border_lines: [ :dotted ] }) do
          row(0).font_style = :bold
          row(0).align = :center
          row(0).border_lines = [ :dashed ]
          row(0).border_width = 2
          cells.padding = 8
        end
        pdf.move_down 20

        # Total price
        pdf.text "Price: $#{@sale.amount.round(2)}", size: 24, style: :bold, align: :center
        pdf.move_down 20
        pdf.text "Thank You!", align: :center, size: 20
      end
    end

    def line_items_table
      item_index = 0
      [ [ "No.", "Name", "Size", "Sugar", "Price" ] ] +
        @sale.product_sales.map do |product_sale|
          item_index += 1
          [ "#{item_index}.", product_sale.product_size.product.name, product_sale.product_size.size, "#{product_sale.sugar_level} %", "$#{product_sale.price.round(2)}" ]
        end
    end
end

app/views/sales/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@sale) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :code
    = f.input :status
    = f.input :customer_name
    = f.input :customer_phone_number
    = f.input :note
    = f.association :user

  .form-actions
    = f.button :submit

app/views/sales/edit.html.haml
%h1 Editing sale

= render 'form'

= link_to 'Show', @sale
\|
= link_to 'Back', sales_path

app/views/sales/index.html.haml
.row
  .col-lg-12.d-flex.align-items-stretch
    .card.w-100
      .card-body.p-4
        %h5.card-title.fw-semibold.mb-4
          %i.ti.ti-filter
          Filter Sale Records
        .row
          .col-md-12
            = datagrid_form_for @grid, :method => :get, :url => sales_path

.row
  .col-lg-12.d-flex.align-items-stretch
    .card.w-100
      .card-body.p-4
        %h5.card-title.fw-semibold.mb-4
          %i.ti.ti-report-money
          All Sale Records
        .table-responsive
          = datagrid_table @grid
        = render "partials/pagination"

app/views/sales/new.html.haml
%h1 New sale

= render 'form'

= link_to 'Back', sales_path

app/views/sales/show.html.haml
= link_to sales_path, class: "btn btn-light" do
  %i.ti.ti-arrow-left
  Back to Sale Records

= link_to sale_path(@sale, format: :pdf), class: "btn btn-dark m-l-10", target: "_blank" do
  %i.ti.ti-printer
  Print Invoice

%br/
%br/
.row
  .col-sm-12.col-lg-5.d-flex.align-items-stretch
    .card.w-100
      .card-body.p-4
        %h5.card-title.fw-semibold.mb-4
          %i.ti.ti-report-money
          Sale Record Detail
          = render_sale_status(@sale, "float: right;")
        .table-responsive
          %table.table.table-bordered.custom-table
            %tbody.body-add-p-10
              %tr
                %td{style: "width: 30%"} Code
                %th= @sale.code
              %tr
                %td Customer
                %th= @sale.customer_name
              %tr
                %td Phone
                %th= @sale.customer_phone_number
              %tr
                %td Sold By
                %th= link_to @sale.user.name, user_path(@sale.user)
              %tr
                %td Date
                %th= @sale.created_at.strftime("%B %d, %Y %I:%M %p")
              %tr
                %td{colspan: 2}
                  Note:
                  = @sale.note

  .col-sm-12.col-lg-7.d-flex.align-items-stretch
    .card.w-100
      .card-body.p-4
        %h5.card-title.fw-semibold.mb-4
          %i.ti.ti-package
          Sale Items
          %span.badge.bg-primary.rounded-3.fw-semibold{style: "float: right;"}
            = "#{@sale.total_items} Item(s)"
        .table-responsive
          %table.table
            %thead
              %tr
                %th Picture
                %th Product
                %th.text-center Size
                %th.text-center Sugar
                %th.text-center $ Price
            %tbody.body-add-p-10
              - @sale.product_sales.each do |product_sale|
                - product = product_sale.product_size.product
                %tr
                  %td= image_tag product.picture_as_thumbnail, class: "img-fluid rounded", style: "max-width: 100px" if product.picture.attached?
                  %td= product.name
                  %td.text-center= product_sale.product_size.size
                  %td.text-center= "#{product_sale.sugar_level} %"
                  %td.text-center= "$ #{product_sale.price.round(2)}"
              %tr
                %td.text-end{colspan: 4}
                  %b Total:
                %td.text-center
                  %b= "$ #{'%.2f' % @sale.amount}"

app/views/sales/show.pdf.haml
%h1 Hello World
%h3
  Invoice Number
  %b= @sale.code